shared-config:
  port: 8082
  name: publisher-service
  db:
    base-url: jdbc:postgresql://localhost:5433 #5432 normalement
    username: postgres
    password: root
    driver: org.postgresql.Driver
  kafka:
    bootstrap: localhost:9092
    group: publisher-service-group
    schema-registry: http://localhost:8081

server:
  port: ${shared-config.port}

logging:
  level:
    org.springframework: WARN
    org.apache.kafka: WARN
    io.confluent: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: WARN

spring:
  application:
    name: ${shared-config.name}

  datasource:
    publisher:
      url: ${shared-config.db.base-url}/publisher_db
      username: ${shared-config.db.username}
      password: ${shared-config.db.password}
      driver-class-name: ${shared-config.db.driver}
    distributor:
      url: ${shared-config.db.base-url}/distributor_db
      username: ${shared-config.db.username}
      password: ${shared-config.db.password}
      driver-class-name: ${shared-config.db.driver}
    player:
      url: ${shared-config.db.base-url}/player_db
      username: ${shared-config.db.username}
      password: ${shared-config.db.password}
      driver-class-name: ${shared-config.db.driver}

  jpa:
    open-in-view: false
    hibernate: #ajout
      ddl-auto: update  #ajout
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect   #ajout
        show_sql: true  #ajout pour afficher ce que fait Hibernate
        format_sql: true  #ajout pour afficher ce que fait Hibernate
        hbm2ddl.auto: update   #none pou update

  kafka:
    bootstrap-servers: ${shared-config.kafka.bootstrap}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: ${shared-config.kafka.group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: ${shared-config.kafka.schema-registry}
      specific.avro.reader: true